
from django.contrib import admin
from .models import PartenaireBDE,BDEMission,BDE, MissionBDE, MissionBDA,BDAMission,BDA,ClubClubs,Clubs,Club,Sport,Partenaire,Deplome,Reseau,AlumniReseau,AlumniDeplome,AlumniHistoire,Histoire,News, Objec, Formati,FormationObjec,Prof,FormationProf,Prerequi,FormationPrerequi,Alumni,Retour,AlumniRetour
admin.site.register(News)
admin.site.register(Formati)
admin.site.register(Objec)
admin.site.register(FormationObjec)
admin.site.register(Prof)
admin.site.register(FormationProf)
admin.site.register(Prerequi)
admin.site.register(FormationPrerequi)
admin.site.register(Alumni)
admin.site.register(Retour)
admin.site.register(AlumniRetour)
admin.site.register(Histoire)
admin.site.register(AlumniHistoire)
admin.site.register(Deplome)
admin.site.register(AlumniDeplome)
admin.site.register(Reseau)
admin.site.register(AlumniReseau)
admin.site.register(Partenaire)
admin.site.register(Sport)
admin.site.register(Club)
admin.site.register(ClubClubs)
admin.site.register(Clubs)
admin.site.register(BDA)
admin.site.register(BDAMission)
admin.site.register(MissionBDA)
admin.site.register(BDE)
admin.site.register(BDEMission)
admin.site.register(MissionBDE)
admin.site.register(PartenaireBDE)