from django.urls import path
from .views import Alumnidelete,AlumniDetail,AlumniUpdate,Deplomedelete,DeplomeCreate,DeplomeDetail,DeplomeList,DeplomeUpdate,ReseauUpdate,ReseauCreate,Reseaudelete,ReseauList,ReseauDetail,HistoireUpdate,RetourDetail,HistoireCreate,HistoireList,Histoiredelete,HistoireDetail,RetourDetail,RetourList,RetourUpdate,Retourdelete,RetourCreate,Prerequisitedelete,PrerequisiteUpdate,PrerequisiteCreate,PrerequisiteDetail,PrerequisiteList,Objectifdelete,ObjectifUpdate, ObjectifCreate,ObjectifDetail,ObjectifsList,ObjectifList,Profdelete,ProfUpdate,ProfCreate,ProfDetail,ProfsList,ProfList, FormationDetail,FormationCreate,Formationdelete,FormationUpdate,FormationCreate,FormationsList,FormationList, EquipesList,EquipeDetail,EquipeCreate,EquipeUpdate,Equipedelete,EquipeList, NewsList ,NewsDetail,NewsCreate ,NewsUpdate,Newsdelete , CustomLoginView ,RegisterPage,HomeView ,HOMEView ,EventList ,EventDetail,EventCreate ,EventUpdate,Eventdelete,Events_List,NewssList
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from . import views

# URL configuration
urlpatterns = [
 path ('login/',CustomLoginView.as_view(),name ='login'), 
 path ('logout/',LogoutView.as_view(next_page = 'login'),name ='logout'),   
 path ('register/',RegisterPage.as_view(),name ='register'),   
 path ('news',NewsList.as_view(),name ='news_list'),
 path ('News',NewssList.as_view(),name ='NewsList'),
 path ('home' ,HomeView.as_view(),name ='home'),
 path ('' ,HOMEView.as_view(),name ='Acceuil'),
 path ('create_news/',NewsCreate.as_view(),name ='news_create'),
 path ('update_news/<int:pk>/',NewsUpdate.as_view(),name ='news_update'),
 path ('news/<int:pk>/',NewsDetail.as_view(),name ='news'),
 path ('delete_news/<int:pk>/',Newsdelete.as_view(),name ='news_delete'),
 path ('events',EventList.as_view(),name ='event_list'),
 path ('Events',Events_List.as_view(),name ='EventsList'),
 path ('create_event/',EventCreate.as_view(),name ='event_create'),
 path ('update_event/<int:pk>/',EventUpdate.as_view(),name ='event_update'),
 path ('event/<int:pk>/',EventDetail.as_view(),name ='event'),
 path ('delete_event/<int:pk>/',Eventdelete.as_view(),name ='event_delete'),
 path ('equipe',EquipeList.as_view(),name ='equipe_list'),
 path ('equipes',EquipesList.as_view(),name ='EquipeList'),
 path ('create_equipe/',EquipeCreate.as_view(),name ='equipe_create'),
 path ('update_equipe/<int:pk>/',EquipeUpdate.as_view(),name ='equipe_update'),
 path ('equipe/<int:pk>/',EquipeDetail.as_view(),name ='equipe'),
 path ('delete_equipe/<int:pk>/',Equipedelete.as_view(),name ='equipe_delete'),
 path ('formation',FormationList.as_view(),name ='formation_list'),
 path ('Formation',FormationsList.as_view(),name ='Acceuil'),
 path ('create_formation/',FormationCreate.as_view(),name ='formati_create'),
 path ('update_formation/<int:pk>/',FormationUpdate.as_view(),name ='formati_update'),
 path ('formation/<int:pk>/',FormationDetail.as_view(),name ='formati'),
 path ('delete_formation/<int:pk>/',Formationdelete.as_view(),name ='formati_delete'),
 path ('profs',ProfList.as_view(),name ='prof_list'),
 path ('Prof',ProfsList.as_view(),name ='ProfsList'),
 path ('create_prof/',ProfCreate.as_view(),name ='prof_create'),
 path ('update_prof/<int:pk>/',ProfUpdate.as_view(),name ='prof_update'),
 path ('prof/<int:pk>/',ProfDetail.as_view(),name ='prof'),
 path ('delete_prof/<int:pk>/',Profdelete.as_view(),name ='prof_delete'),
 path ('objectif',ObjectifList.as_view(),name ='objectif_list'),
 path ('Objectif',ObjectifsList.as_view(),name ='ObjectifList'),
 path ('create_objectif/',ObjectifCreate.as_view(),name ='objectif_create'),
 path ('update_objectif/<int:pk>/',ObjectifUpdate.as_view(),name ='objectif_update'),
 path ('objectif/<int:pk>/',ObjectifDetail.as_view(),name ='objectif'),
 path ('delete_objectif/<int:pk>/',Objectifdelete.as_view(),name ='objectif_delete'),
 path ('prerequisites',PrerequisiteList.as_view(),name ='prerequisite_list'),
 path ('create_prerequisite/',PrerequisiteCreate.as_view(),name ='prerequisite_create'),
 path ('update_prerequisite/<int:pk>/',PrerequisiteUpdate.as_view(),name ='prerequisite_update'),
 path ('prerequisite/<int:pk>/',PrerequisiteDetail.as_view(),name ='prerequisite'),
 path ('delete_prerequisite/<int:pk>/',Prerequisitedelete.as_view(),name ='prerequisite_delete'),
 path ('retours',RetourList.as_view(),name ='retour_list'),
 path ('create_retour/',RetourCreate.as_view(),name ='retour_create'),
 path ('update_retour/<int:pk>/',RetourUpdate.as_view(),name ='retour_update'),
 path ('retour/<int:pk>/',RetourDetail.as_view(),name ='retour'),
 path ('delete_retour/<int:pk>/',Retourdelete.as_view(),name ='retour_delete'),
 path ('histoires',HistoireList.as_view(),name ='histoire_list'),
 path ('create_histoire/',HistoireCreate.as_view(),name ='histoire_create'),
 path ('update_histoire/<int:pk>/',HistoireUpdate.as_view(),name ='histoire_update'),
 path ('histoire/<int:pk>/',HistoireDetail.as_view(),name ='histoire'),
 path ('delete_histoire/<int:pk>/',Histoiredelete.as_view(),name ='histoire_delete'),
 path ('reseau',ReseauList.as_view(),name ='reseau_list'),
 path ('create_reseau/',ReseauCreate.as_view(),name ='reseau_create'),
 path ('update_reseau/<int:pk>/',ReseauUpdate.as_view(),name ='reseau_update'),
 path ('reseau/<int:pk>/',ReseauDetail.as_view(),name ='reseau'),
 path ('delete_reseau/<int:pk>/',Reseaudelete.as_view(),name ='reseau_delete'),
 path ('deplome',DeplomeList.as_view(),name ='deplome_list'),
 path ('create_deplome/',DeplomeCreate.as_view(),name ='deplome_create'),
 path ('update_deplome/<int:pk>/',DeplomeUpdate.as_view(),name ='deplome_update'),
 path ('deplome/<int:pk>/',DeplomeDetail.as_view(),name ='deplome'),
 path ('delete_deplome/<int:pk>/',Deplomedelete.as_view(),name ='deplome_delete'),
 path ('alumni/', AlumniDetail.as_view(), name='alumni_detail'),
 path ('alumni/update/', AlumniUpdate.as_view(), name='alumni_update'),
 path ('alumni/delete/', Alumnidelete.as_view(), name='alumni_delete'), 
 path('ecole/', views.ecole, name='ecole'), 
 path('faculte/', views.faculte, name='faculte'), 
 path('mot-president/', views.mot_president, name='mot_president'),
  path('avis_etudiant/', views.avis, name='avis'),
  path('bda/', views.bda, name='bda'),
  path('clubs/', views.club, name='club'),
  path('bde/', views.bde, name='bde'),
  path('E_services/', views.eservice, name='E_services'),
  path('réglements/', views.reglements, name='réglements'),
   path('viesportive/', views.viesportive, name='viesportive'),
   path('partenaires_locaux/', views.partelocaux, name='partenaires_locaux'),
   path('partenaires_internationaux/', views.partein ,name='partenaires_internationaux'),
   path('recruteurs/', views.recrutement ,name='recruteurs'),
   path('stages/', views.stage ,name='stages'),
   path('equipement/', views.equipement ,name='equipement'),



 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)