# Generated by Django 5.1.4 on 2024-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formati',
            name='im',
            field=models.ImageField(null=True, upload_to='formations/'),
        ),
        migrations.AddField(
            model_name='formati',
            name='ima',
            field=models.ImageField(null=True, upload_to='formations/'),
        ),
        migrations.AddField(
            model_name='formati',
            name='imag',
            field=models.ImageField(null=True, upload_to='formations/'),
        ),
    ]
