# Generated by Django 5.1.4 on 2024-12-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_formati_im_formati_ima_formati_imag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='lieu',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
